{self}: {
  config,
  lib,
  pkgs,
  options,
  ...
}: let
  inherit (lib) mkEnableOption mkIf mkOption mkDefault mkMerge types optionalString concatStringsSep;

  cfg = config.programs.omarchyScreensaver;
  system = pkgs.stdenv.hostPlatform.system;
  pkg = cfg.package;
  hasHyprlandHM = options.wayland ? windowManager && options.wayland.windowManager ? hyprland;
  hasHypridle = options.services ? hypridle;
  hyprlandEnabled = hasHyprlandHM && config.wayland.windowManager.hyprland.enable;

  effectNames = [
    "beams"
    "binarypath"
    "blackhole"
    "bouncyballs"
    "bubbles"
    "burn"
    "colorshift"
    "crumble"
    "decrypt"
    "errorcorrect"
    "expand"
    "fireworks"
    "highlight"
    "laseretch"
    "matrix"
    "middleout"
    "orbittingvolley"
    "overflow"
    "pour"
    "print"
    "rain"
    "randomsequence"
    "rings"
    "scattered"
    "slice"
    "slide"
    "smoke"
    "spotlights"
    "spray"
    "swarm"
    "sweep"
    "synthgrid"
    "thunderstorm"
    "unstable"
    "vhstape"
    "waves"
    "wipe"
  ];

  artFile =
    if cfg.art.image != null
    then
      pkgs.callPackage ../packages/art-from-image.nix {
        omarchy-screensaver = pkg;
        image = cfg.art.image;
        width = cfg.art.width;
        height = cfg.art.height;
        mode = cfg.art.mode;
        threshold = cfg.art.threshold;
        invert = cfg.art.invert;
        trim = cfg.art.trim;
      }
    else if cfg.art.file != null
    then cfg.art.file
    else
      pkgs.writeText "omarchy-screensaver-art.txt" (
        if cfg.art.text != null
        then cfg.art.text
        else builtins.readFile ../../share/art/omarchy.txt
      );

  bashList = name: values:
    if values == []
    then "${name}=()"
    else "${name}=(${concatStringsSep " " (map lib.escapeShellArg values)})";

  generatedConfig = ''
    # Generated by programs.omarchyScreensaver — do not edit.
    ART_FILE=${lib.escapeShellArg "${cfg.configDir}/art.txt"}
    WINDOW_CLASS=${lib.escapeShellArg cfg.windowClass}
    TERMINAL=${lib.escapeShellArg cfg.terminal}
    FRAME_RATE=${toString cfg.ttfx.frameRate}
    CANVAS_WIDTH=${toString cfg.ttfx.canvasWidth}
    CANVAS_HEIGHT=${toString cfg.ttfx.canvasHeight}
    ANCHOR_CANVAS=${lib.escapeShellArg cfg.ttfx.anchorCanvas}
    ANCHOR_TEXT=${lib.escapeShellArg cfg.ttfx.anchorText}
    REUSE_CANVAS=${
      if cfg.ttfx.reuseCanvas
      then "1"
      else "0"
    }
    EFFECT_MODE=${lib.escapeShellArg cfg.effects.mode}
    SINGLE_EFFECT=${lib.escapeShellArg (cfg.effects.single or "")}
    FONT_SIZE=${toString cfg.appearance.fontSize}
    HIDE_CURSOR=${
      if cfg.appearance.hideCursor
      then "1"
      else "0"
    }
    SHARE_DIR=${lib.escapeShellArg "${pkg}/share/omarchy-screensaver"}
    SCREENSAVER_BIN=${lib.escapeShellArg "${pkg}/bin/omarchy-screensaver"}
    ${bashList "INCLUDE_EFFECTS" cfg.effects.include}
    ${bashList "EXCLUDE_EFFECTS" cfg.effects.exclude}
    ${bashList "EXTRA_TTFX_ARGS" cfg.ttfx.extraArgs}
  '';

  bg = lib.removePrefix "#" cfg.appearance.background;
  fg = lib.removePrefix "#" cfg.appearance.foreground;

  alacrittyToml = ''
    [colors.primary]
    background = "0x${bg}"

    [colors.cursor]
    cursor = "0x${bg}"

    [font]
    size = ${toString cfg.appearance.fontSize}.0

    [window]
    opacity = 1.0
  '';

  ghosttyConf = ''
    window-padding-x = 0
    window-padding-y = 0
    window-padding-color = "extend-always"
    background = #${bg}
    foreground = #${fg}
    font-size = ${toString cfg.appearance.fontSize}
  '';

  footIni = ''
    [main]
    font=${cfg.appearance.fontFamily}:size=${toString cfg.appearance.fontSize}
    pad=0x0

    [colors-dark]
    background=${bg}
    foreground=${fg}
  '';

  newHyprRules = ''
    windowrule = match:class ${cfg.windowClass}, float on
    windowrule = match:class ${cfg.windowClass}, fullscreen on
    ${optionalString cfg.hyprland.stayFocused "windowrule = match:class ${cfg.windowClass}, stay_focused on"}
    windowrule = match:class ${cfg.windowClass}, animation ${cfg.hyprland.animation}
  '';

  legacyHyprRules = ''
    windowrulev2 = float, class:${cfg.windowClass}
    windowrulev2 = fullscreen, class:${cfg.windowClass}
    ${optionalString cfg.hyprland.stayFocused "windowrulev2 = stayfocused, class:${cfg.windowClass}"}
    windowrulev2 = noanim, class:${cfg.windowClass}
  '';

  hyprRules =
    if cfg.hyprland.ruleSyntax == "legacy"
    then legacyHyprRules
    else newHyprRules;

  hyprBind = optionalString (cfg.bind != null) ''
    bind = ${cfg.bind}, exec, ${pkg}/bin/omarchy-screensaver-launch force
  '';

  hyprSnippet = ''
    # omarchy-screensaver
    ${hyprRules}
    ${hyprBind}
  '';

  hypridleSnippet = ''
    # omarchy-screensaver idle listeners
    listener {
      timeout = ${toString cfg.idle.timeout}
      on-timeout = ${pkg}/bin/omarchy-screensaver-launch
    }
    ${optionalString (cfg.idle.lockTimeout != null) ''
      listener {
        timeout = ${toString cfg.idle.lockTimeout}
        on-timeout = ${cfg.idle.lockCommand}
      }
    ''}
  '';
in {
  options.programs.omarchyScreensaver = {
    enable = mkEnableOption "Omarchy ASCII screensaver for Hyprland";

    package = mkOption {
      type = types.package;
      default =
        if self ? packages && self.packages ? ${system}
        then self.packages.${system}.omarchy-screensaver
        else pkgs.omarchy-screensaver;
      defaultText = "self.packages.\${system}.omarchy-screensaver";
      description = "Screensaver package providing the launch scripts and ttfx wrapper.";
    };

    windowClass = mkOption {
      type = types.str;
      default = "org.omarchy.screensaver";
      description = "Hyprland window class used for fullscreen/float rules.";
    };

    terminal = mkOption {
      type = types.enum ["auto" "alacritty" "foot" "ghostty" "kitty"];
      default = "auto";
      description = "Terminal used to host the screensaver. `auto` picks from xdg-terminal-exec, then kitty/ghostty/foot/alacritty.";
    };

    configDir = mkOption {
      type = types.str;
      default = "${config.xdg.configHome}/omarchy-screensaver";
      defaultText = "\\${config.xdg.configHome}/omarchy-screensaver";
      description = "Directory for generated art and config.";
    };

    bind = mkOption {
      type = types.nullOr types.str;
      default = "SUPER, Escape";
      example = "SUPER, Escape";
      description = "Hyprland bind prefix (without `exec`) that force-starts the screensaver. Set null to skip.";
    };

    art = {
      text = mkOption {
        type = types.nullOr types.lines;
        default = null;
        description = "Inline ASCII/Unicode art. Used when `image` and `file` are unset.";
      };
      file = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "Path to a pre-rendered ASCII art file.";
      };
      image = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "PNG or SVG converted to ASCII at build time via ImageMagick (braille or block).";
      };
      width = mkOption {
        type = types.ints.positive;
        default = 80;
        description = "Max columns when converting `art.image`.";
      };
      height = mkOption {
        type = types.ints.positive;
        default = 26;
        description = "Max rows when converting `art.image`.";
      };
      mode = mkOption {
        type = types.enum ["braille" "block"];
        default = "braille";
        description = "Glyph style for image conversion. Braille is finer.";
      };
      threshold = mkOption {
        type = types.ints.between 0 100;
        default = 50;
        description = "Percent threshold for which pixels count as the logo.";
      };
      invert = mkOption {
        type = types.bool;
        default = false;
        description = "Treat light pixels as the logo (for light-on-dark source images).";
      };
      trim = mkOption {
        type = types.bool;
        default = true;
        description = "Trim surrounding empty background before converting.";
      };
    };

    effects = {
      mode = mkOption {
        type = types.enum ["random" "single"];
        default = "random";
        description = "Pick a random ttfx effect each cycle, or always run `effects.single`.";
      };
      single = mkOption {
        type = types.nullOr (types.enum effectNames);
        default = null;
        description = "Effect used when `mode = \"single\"`.";
      };
      include = mkOption {
        type = types.listOf (types.enum effectNames);
        default = [];
        description = "When random, only these effects (empty = all, minus exclude).";
      };
      exclude = mkOption {
        type = types.listOf (types.enum effectNames);
        default = [];
        description = "Effects skipped by `--random-effect`.";
      };
    };

    ttfx = {
      frameRate = mkOption {
        type = types.ints.unsigned;
        default = 120;
        description = "ttfx frame rate. Omarchy uses 120.";
      };
      canvasWidth = mkOption {
        type = types.int;
        default = 0;
        description = "ttfx `--canvas-width`. 0 = terminal width.";
      };
      canvasHeight = mkOption {
        type = types.int;
        default = 0;
        description = "ttfx `--canvas-height`. 0 = terminal height.";
      };
      reuseCanvas = mkOption {
        type = types.bool;
        default = true;
        description = "Pass `--reuse-canvas` so cycles don't flash.";
      };
      anchorCanvas = mkOption {
        type = types.str;
        default = "c";
        description = "Canvas anchor (n/s/e/w/c and diagonals).";
      };
      anchorText = mkOption {
        type = types.str;
        default = "c";
        description = "Text anchor inside the canvas.";
      };
      extraArgs = mkOption {
        type = types.listOf types.str;
        default = [];
        description = "Extra args appended to ttfx.";
      };
    };

    appearance = {
      fontSize = mkOption {
        type = types.ints.positive;
        default = 18;
        description = "Terminal font size for the screensaver window.";
      };
      fontFamily = mkOption {
        type = types.str;
        default = "JetBrainsMono Nerd Font";
        description = "Font family used in the foot screensaver config.";
      };
      background = mkOption {
        type = types.str;
        default = "000000";
        description = "Background hex without or with leading #.";
      };
      foreground = mkOption {
        type = types.str;
        default = "ffffff";
        description = "Foreground hex without or with leading #.";
      };
      hideCursor = mkOption {
        type = types.bool;
        default = true;
        description = "Hide the Hyprland cursor while the screensaver is up.";
      };
    };

    idle = {
      enable = mkEnableOption "hypridle listeners for screensaver + lock" // {default = true;};
      timeout = mkOption {
        type = types.ints.positive;
        default = 150;
        description = "Seconds after idle before the screensaver launches. Counted from idle start, not from the previous listener.";
      };
      lockTimeout = mkOption {
        type = types.nullOr types.ints.positive;
        default = 300;
        description = "Seconds after idle before lockCommand. Null disables the lock listener.";
      };
      lockCommand = mkOption {
        type = types.str;
        default = "loginctl lock-session";
        description = "Command run at lockTimeout. Typical: hyprlock or loginctl lock-session.";
      };
      manageHypridle = mkOption {
        type = types.bool;
        default = true;
        description = "Append screensaver listeners via services.hypridle.extraConfig. Disable if you wire hypridle yourself.";
      };
    };

    hyprland = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Install Hyprland window rules and optional bind.";
      };
      ruleSyntax = mkOption {
        type = types.enum ["new" "legacy"];
        default = "new";
        description = "`new` is Hyprland 0.53+ (`windowrule = match:class …`). `legacy` emits windowrulev2.";
      };
      stayFocused = mkOption {
        type = types.bool;
        default = false;
        description = "Keep the screensaver focused (can fight bars/panels).";
      };
      animation = mkOption {
        type = types.str;
        default = "slide";
        description = "Hyprland animation for the screensaver window. Use `none` to disable.";
      };
      injectExtraConfig = mkOption {
        type = types.bool;
        default = true;
        description = "Append rules to wayland.windowManager.hyprland.extraConfig when that module is on.";
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      assertions = [
        {
          assertion = !(cfg.effects.mode == "single" && cfg.effects.single == null);
          message = "programs.omarchyScreensaver.effects.single must be set when effects.mode = \"single\".";
        }
        {
          assertion = !(cfg.effects.include != [] && cfg.effects.exclude != []);
          message = "programs.omarchyScreensaver.effects.include and exclude are mutually exclusive (ttfx constraint).";
        }
      ];

      home.packages = [pkg];

      xdg.configFile."omarchy-screensaver/art.txt".source = artFile;
      xdg.configFile."omarchy-screensaver/config".text = generatedConfig;
      xdg.configFile."omarchy-screensaver/terminals/alacritty.toml".text = alacrittyToml;
      xdg.configFile."omarchy-screensaver/terminals/ghostty".text = ghosttyConf;
      xdg.configFile."omarchy-screensaver/terminals/foot.ini".text = footIni;
      xdg.configFile."hypr/omarchy-screensaver.conf".text = hyprSnippet;

      home.sessionVariables.OMARCHY_SCREENSAVER_CONFIG = "${cfg.configDir}/config";
    }
    (mkIf (cfg.hyprland.enable && cfg.hyprland.injectExtraConfig && hyprlandEnabled) {
      wayland.windowManager.hyprland.extraConfig = lib.mkAfter ''
        source = ${config.xdg.configHome}/hypr/omarchy-screensaver.conf
      '';
    })
    (mkIf (cfg.idle.enable && cfg.idle.manageHypridle && hasHypridle && hyprlandEnabled) {
      services.hypridle.enable = mkDefault true;
      services.hypridle.extraConfig = lib.mkAfter hypridleSnippet;
    })
  ]);
}
