{
  lib,
  pkgs,
  cfg,
  pkg,
}: let
  inherit (lib) optionalString concatStringsSep;

  artFile =
    if cfg.art.image != null
    then
      pkgs.callPackage ../packages/art-from-image.nix {
        omarchy-screensaver = pkg;
        image = cfg.art.image;
        width = cfg.art.width;
        height = cfg.art.height;
        mode = cfg.art.mode;
        threshold = cfg.art.threshold;
        invert = cfg.art.invert;
        trim = cfg.art.trim;
      }
    else if cfg.art.file != null
    then cfg.art.file
    else
      pkgs.writeText "omarchy-screensaver-art.txt" (
        if cfg.art.text != null
        then cfg.art.text
        else builtins.readFile ../../share/art/omarchy.txt
      );

  bashList = name: values:
    if values == []
    then "${name}=()"
    else "${name}=(${concatStringsSep " " (map lib.escapeShellArg values)})";

  generatedConfig = ''
    # Generated by programs.omarchyScreensaver — do not edit.
    ART_FILE=${lib.escapeShellArg "${cfg.configDir}/art.txt"}
    WINDOW_CLASS=${lib.escapeShellArg cfg.windowClass}
    TERMINAL=${lib.escapeShellArg cfg.terminal}
    COMPOSITOR=${lib.escapeShellArg cfg.compositor}
    FRAME_RATE=${toString cfg.ttfx.frameRate}
    CANVAS_WIDTH=${toString cfg.ttfx.canvasWidth}
    CANVAS_HEIGHT=${toString cfg.ttfx.canvasHeight}
    ANCHOR_CANVAS=${lib.escapeShellArg cfg.ttfx.anchorCanvas}
    ANCHOR_TEXT=${lib.escapeShellArg cfg.ttfx.anchorText}
    REUSE_CANVAS=${
      if cfg.ttfx.reuseCanvas
      then "1"
      else "0"
    }
    EFFECT_MODE=${lib.escapeShellArg cfg.effects.mode}
    SINGLE_EFFECT=${lib.escapeShellArg (cfg.effects.single or "")}
    FONT_SIZE=${toString cfg.appearance.fontSize}
    HIDE_CURSOR=${
      if cfg.appearance.hideCursor
      then "1"
      else "0"
    }
    SHARE_DIR=${lib.escapeShellArg "${pkg}/share/omarchy-screensaver"}
    SCREENSAVER_BIN=${lib.escapeShellArg "${pkg}/bin/omarchy-screensaver"}
    ${bashList "INCLUDE_EFFECTS" cfg.effects.include}
    ${bashList "EXCLUDE_EFFECTS" cfg.effects.exclude}
    ${bashList "EXTRA_TTFX_ARGS" cfg.ttfx.extraArgs}
  '';

  bg = lib.removePrefix "#" cfg.appearance.background;
  fg = lib.removePrefix "#" cfg.appearance.foreground;
  bgTok = cfg.appearance.noctalia.background;
  fgTok = cfg.appearance.noctalia.foreground;
  colorHex = tok: "{{ colors.${tok}.default.hex }}";
  colorHexBare = tok: "{{ colors.${tok}.default.hex_stripped }}";

  alacrittyToml = ''
    [colors.primary]
    background = "0x${bg}"
    foreground = "0x${fg}"

    [colors.cursor]
    cursor = "0x${bg}"

    [font]
    size = ${toString cfg.appearance.fontSize}.0

    [window]
    opacity = 1.0
    decorations = "None"
    startup_mode = "Fullscreen"
  '';

  alacrittyTpl = ''
    [colors.primary]
    background = "0x${colorHexBare bgTok}"
    foreground = "0x${colorHexBare fgTok}"

    [colors.cursor]
    cursor = "0x${colorHexBare bgTok}"

    [font]
    size = ${toString cfg.appearance.fontSize}.0

    [window]
    opacity = 1.0
    decorations = "None"
    startup_mode = "Fullscreen"
  '';

  ghosttyConf = ''
    window-padding-x = 0
    window-padding-y = 0
    window-padding-color = "extend-always"
    window-decoration = false
    fullscreen = true
    background = #${bg}
    foreground = #${fg}
    font-size = ${toString cfg.appearance.fontSize}
  '';

  ghosttyTpl = ''
    window-padding-x = 0
    window-padding-y = 0
    window-padding-color = "extend-always"
    window-decoration = false
    fullscreen = true
    background = ${colorHex bgTok}
    foreground = ${colorHex fgTok}
    font-size = ${toString cfg.appearance.fontSize}
  '';

  footIni = ''
    [main]
    font=${cfg.appearance.fontFamily}:size=${toString cfg.appearance.fontSize}
    pad=0x0

    [colors-dark]
    background=${bg}
    foreground=${fg}

    [csd]
    preferred=none
  '';

  footTpl = ''
    [main]
    font=${cfg.appearance.fontFamily}:size=${toString cfg.appearance.fontSize}
    pad=0x0

    [colors-dark]
    background=${colorHexBare bgTok}
    foreground=${colorHexBare fgTok}

    [csd]
    preferred=none
  '';

  kittyConf = ''
    font_size ${toString cfg.appearance.fontSize}
    window_padding_width 0
    hide_window_decorations yes
    confirm_os_window_close 0
    remember_window_size no
    allow_remote_control no
    background #${bg}
    foreground #${fg}
    cursor #${bg}
  '';

  kittyTpl = ''
    font_size ${toString cfg.appearance.fontSize}
    window_padding_width 0
    hide_window_decorations yes
    confirm_os_window_close 0
    remember_window_size no
    allow_remote_control no
    background ${colorHex bgTok}
    foreground ${colorHex fgTok}
    cursor ${colorHex bgTok}
  '';

  hyprlandOn = cfg.hyprland.enable || cfg.compositor != "kwin";
  kwinOn = cfg.compositor != "hyprland";

  newHyprRules = ''
    windowrule = match:class ${cfg.windowClass}, float on
    windowrule = match:class ${cfg.windowClass}, fullscreen on
    ${optionalString cfg.hyprland.stayFocused "windowrule = match:class ${cfg.windowClass}, stay_focused on"}
    windowrule = match:class ${cfg.windowClass}, animation ${cfg.hyprland.animation}
  '';

  legacyHyprRules = ''
    windowrulev2 = float, class:${cfg.windowClass}
    windowrulev2 = fullscreen, class:${cfg.windowClass}
    ${optionalString cfg.hyprland.stayFocused "windowrulev2 = stayfocused, class:${cfg.windowClass}"}
    windowrulev2 = noanim, class:${cfg.windowClass}
  '';

  hyprRules =
    if cfg.hyprland.ruleSyntax == "legacy"
    then legacyHyprRules
    else newHyprRules;

  hyprBind = optionalString (cfg.hyprland.bind != null && hyprlandOn) ''
    bind = ${cfg.hyprland.bind}, exec, ${pkg}/bin/omarchy-screensaver-launch force
  '';

  hyprSnippet = ''
    # omarchy-screensaver
    ${hyprRules}
    ${hyprBind}
  '';

  hypridleSnippet = ''
    # omarchy-screensaver idle listeners
    listener {
      timeout = ${toString cfg.idle.timeout}
      on-timeout = ${pkg}/bin/omarchy-screensaver-launch
    }
    ${optionalString (cfg.idle.manageLock && cfg.idle.lockTimeout != null) ''
      listener {
        timeout = ${toString cfg.idle.lockTimeout}
        on-timeout = ${cfg.idle.lockCommand}
      }
    ''}
  '';

  orderParts =
    ["\"screensaver\""]
    ++ lib.optionals (cfg.idle.manageLock && cfg.idle.lockTimeout != null) ["\"lock\""]
    ++ ["\"screen-off\"" "\"suspend\""];

  noctaliaToml = ''
    # Generated by programs.omarchyScreensaver.
    # Noctalia v5 merges every *.toml in ~/.config/noctalia/ alphabetically;
    # zz- so these idle keys and user templates win over config.toml without replacing the rest.
    ${optionalString (cfg.idle.enable && cfg.idle.backend == "noctalia") ''
      ${optionalString cfg.idle.writeBehaviorOrder ''
        [idle]
        behavior_order = [${lib.concatStringsSep ", " orderParts}]
        ${optionalString (cfg.idle.preActionFade != null) "pre_action_fade_seconds = ${toString cfg.idle.preActionFade}"}
      ''}
      [idle.behavior.screensaver]
      enabled = true
      timeout = ${toString cfg.idle.timeout}
      action = "command"
      command = ${builtins.toJSON "${pkg}/bin/omarchy-screensaver-launch"}

      ${optionalString (cfg.idle.manageLock && cfg.idle.lockTimeout != null) ''
        [idle.behavior.lock]
        enabled = true
        timeout = ${toString cfg.idle.lockTimeout}
        action = "lock"
      ''}
    ''}
    ${optionalString cfg.appearance.noctalia.enable ''
      # Live palette → screensaver terminals. Defining [theme.templates.user.<id>] enables it.
      [theme.templates.user.omarchy_screensaver_alacritty]
      input_path  = "$XDG_CONFIG_HOME/omarchy-screensaver/templates/alacritty.toml"
      output_path = "$XDG_CONFIG_HOME/omarchy-screensaver/terminals/alacritty.toml"

      [theme.templates.user.omarchy_screensaver_ghostty]
      input_path  = "$XDG_CONFIG_HOME/omarchy-screensaver/templates/ghostty"
      output_path = "$XDG_CONFIG_HOME/omarchy-screensaver/terminals/ghostty"

      [theme.templates.user.omarchy_screensaver_foot]
      input_path  = "$XDG_CONFIG_HOME/omarchy-screensaver/templates/foot.ini"
      output_path = "$XDG_CONFIG_HOME/omarchy-screensaver/terminals/foot.ini"

      [theme.templates.user.omarchy_screensaver_kitty]
      input_path  = "$XDG_CONFIG_HOME/omarchy-screensaver/templates/kitty.conf"
      output_path = "$XDG_CONFIG_HOME/omarchy-screensaver/terminals/kitty.conf"
    ''}
  '';

  desktopEntry = ''
    [Desktop Entry]
    Type=Application
    Name=Omarchy Screensaver
    Comment=Force-start the ASCII screensaver
    Exec=${pkg}/bin/omarchy-screensaver-launch force
    Icon=preferences-desktop-screensaver
    Terminal=false
    Categories=Utility;
    StartupNotify=false
    ${optionalString (cfg.bind != null) "X-KDE-Shortcuts=${cfg.bind}"}
  '';

  terminalFiles = {
    "omarchy-screensaver/terminals/alacritty.toml".text = alacrittyToml;
    "omarchy-screensaver/terminals/ghostty".text = ghosttyConf;
    "omarchy-screensaver/terminals/foot.ini".text = footIni;
    "omarchy-screensaver/terminals/kitty.conf".text = kittyConf;
  };

  templateFiles = {
    "omarchy-screensaver/templates/alacritty.toml".text = alacrittyTpl;
    "omarchy-screensaver/templates/ghostty".text = ghosttyTpl;
    "omarchy-screensaver/templates/foot.ini".text = footTpl;
    "omarchy-screensaver/templates/kitty.conf".text = kittyTpl;
  };

  configFiles =
    {
      "omarchy-screensaver/art.txt".source = artFile;
      "omarchy-screensaver/config".text = generatedConfig;
    }
    // lib.optionalAttrs (!cfg.appearance.noctalia.enable) terminalFiles
    // lib.optionalAttrs cfg.appearance.noctalia.enable templateFiles;

  noctaliaFile = {
    "noctalia/zz-omarchy-screensaver.toml".text = noctaliaToml;
  };

  hyprFile = {
    "hypr/omarchy-screensaver.conf".text = hyprSnippet;
  };

  assertions = [
    {
      assertion = !(cfg.effects.mode == "single" && cfg.effects.single == null);
      message = "programs.omarchyScreensaver.effects.single must be set when effects.mode = \"single\".";
    }
    {
      assertion = !(cfg.effects.include != [] && cfg.effects.exclude != []);
      message = "programs.omarchyScreensaver.effects.include and exclude are mutually exclusive (ttfx constraint).";
    }
  ];
in {
  inherit
    artFile
    generatedConfig
    configFiles
    noctaliaFile
    hyprFile
    noctaliaToml
    desktopEntry
    hyprSnippet
    hypridleSnippet
    hyprlandOn
    kwinOn
    assertions
    ;
  writeNoctaliaIdle = cfg.idle.enable && cfg.idle.backend == "noctalia";
  writeNoctaliaTheme = cfg.appearance.noctalia.enable;
  writeNoctalia = writeNoctaliaIdle || writeNoctaliaTheme;
  writeHypridle = cfg.idle.enable && cfg.idle.backend == "hypridle";
  writeHypr = hyprlandOn;
  writeDesktop = kwinOn && cfg.kwin.desktopShortcut && cfg.bind != null;
}
